;; Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
;;    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;; By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
(defun calc_sum_even_fib()
  (let ((prev 0)
	(actual 1)
	(sum 0))
    (loop
       (when (> actual 4000000) (return sum))
       (let ((next (+ prev actual)))
	 (if (eq (mod actual 2) 0)
	     (setq sum (+ sum actual)))
	 (setq prev actual)
	 (setq actual next)))))
